spring:
  application:
    name: SeemscleverAPIGateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: task-service-route
              uri: http://localhost:8181
              predicates:
                - Path=/internal/api/v1/tasks/**,/swagger-ui/**,/v3/api-docs/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

            - id: auth-service-internal-route
              uri: http://localhost:8183
              predicates:
                - Path=/internal/api/v1/users/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

            - id: auth-service-route
              uri: http://localhost:8183
              predicates:
                - Path=/public/auth/**,/public/api/v1/users/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

springdoc:
  swagger-ui:
    urls:
      - name: task-service
        url: /api/v1/tasks/v3/api-docs
      - name: auth-service
        url: /auth/v3/api-docs


server:
  port: 8180
  forward-headers-strategy: framework

jwt:
  secret: 37e3cc4ade6f6fe1897f96dc1ecf354ef62be84b76a85c0b2027cb8379e5235d
